config/routes.rb
TodoApp::Application.routes.draw do
  resources :projects do
    resources :items, only: [:new]
  end
  
  resources :items
  
  resources :teams do
    resources :projects, only: [:new]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :complete, :description, :title, :project_id
  
  belongs_to :project
  
  validates :title, :description, presence: true
  validates :title, length: { maximum: 25 }
  validates :description, length: { maximum: 400 }
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :team_id
  
  has_many :items
  belongs_to :team
  
  validates :title, :description, :presence => true
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :user_ids
  
  has_many :projects
  has_many :team_memberships
  has_many :users, :through => :team_memberships
  
  validates :name, presence: true
end

app/models/team_membership.rb
class TeamMembership < ActiveRecord::Base
  # attr_accessible
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :eye_color, :team_ids
  
  has_many :team_memberships
  has_many :teams, :through => :team_memberships
  
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def new
    @item = Item.new
    @item.project_id = params[:project_id]
  end
  
  def create
   @item = Item.new(params[:item])
   if @item.save
     redirect_to item_url(@item)
   else
     render :new
   end
  end
  
  def edit
    @item = Item.find(params[:id])
    @item.project_id = params[:project_id]
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      redirect_to :back
    else
      render :edit
    end
  end
  
  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new    
    @project.team_id = params[:team_id]
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save  
      redirect_to project_url(@project)
    else
      render :new
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to project_url(@project)
    else
      render :edit
    end
  end
  
  def destroy
    Project.find(params[:id]).destroy
    redirect_to projects_url
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
  
  def show
    @team = Team.find(params[:id])
  end
  
  def new
    @team = Team.new
  end
  
  def create
    @team = Team.new(params[:team])
    if @team.save
      redirect_to team_path(@team)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_edit_select.html.erb
<%= form_for(item) do |f| %>

		<%= f.label :complete, hidden: true %>
		<%= f.select :complete, [["In Progress", false], ["Complete", true]] %>
		
		<%= f.label :project_id, hidden: true %>
		<%= f.collection_select :project_id, Project.all, :id, :title %>
		<%= f.submit %>
	<!-- ajax would be nice here :) -->
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
<ul>
	<% @item.errors.full_messages.each do |error|%>
		<li><%= error %></li>
	<% end %>
</ul>
	<label>
		Project
		<%= f.collection_select :project_id, Project.all, :id, :title %>
		<br>
	</label>

	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br>
	
	<%= f.label :description %><br>
	<%= f.text_area :description %>
	<br>
	<label>
		Status
		<%= f.select :complete, [["In Progress", false], ["Complete", true]] %>
	</label>
	<%= f.submit "Add Item" %>
<% end %>

<!--
hmm...
rails is quite nice! :)

 <form action="<%= items_path %>", method="post">
	<select name="item[project_id]">
		<% Project.all.each do |project| %>
			<option value="<%= project.id%>" selected="<%= @item.project_id == project.id %>"><%= project.title%></option>
		<% end %>
	</select><br>
	
	<label>
		Title
		<input type="text" name="item[title]">
	</label><br>
	<label>
		Description
		<textarea rows="4" cols="50" name="item[description]">
		</textarea>
	</label><br>
	
	<label>
		Status
		<select name="item[complete]">
			<option value="false">In Progress</option>
			<option value="true">Complete</option>
		</select>
	</label><br>
	
	<input type="submit" value="Add Item">
</form> -->

app/views/items/_items.html.erb
<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th>Status | Project</th>
	</tr>
<% items.each do |item| %>
	<tr>
		<td><%= link_to item.title, item_path(item.id) %></td>
		<td><%= item.description %></td>
		<td><%= render partial: "items/edit_select", locals: { item: item } %></td>
			<!-- make this items project editable from here? -->
		<td><%= button_to "Delete", item_path(item.id),
								method: :delete, confirm: "Are you sure?" %></td>
	</tr>
<% end %>
</table>

app/views/items/edit.html.erb
<h1>Edit Item Details</h1>
<%= render partial: "form" %>

app/views/items/index.html.erb
<h1>All Items</h1>
<%= link_to "add new item", new_item_path%><br><br>
<!-- maybe make each items project editable through select -->
<%= render partial: "items", object: @items %>

app/views/items/new.html.erb
<h1>New ToDo Item</h1>
<%= render partial: 'form' %>

app/views/items/show.html.erb
<h1>ToDo Item</h1>
<%= render partial: "items", object: [@item] %>
<%= link_to "To Project: #{Project.find(@item.project_id).title}", 				project_path(@item.project_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "All Teams", teams_path %>
	<%= link_to "All Projects", projects_path %>
	<%= link_to "All Items", items_path %>
	<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<ul>
	<% @project.errors.full_messages.each do |error|%>
		<li><%= error %></li>
	<% end %>
</ul>
	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
	
	<br>
	
	<label>
		Team
		<%= f.collection_select :team_id, Team.all, :id, :name, :include_blank => true %>
	</label>
	<%= f.submit %>	
<% end %>

app/views/projects/_project.html.erb
<h2> Project : <%= link_to project.title, project_path(project.id) %></h2>

<h3>Team : 
	<%= if project.team_id 
			link_to project.team.name, team_path(project.team_id)
		else
			"Unassigned"
		end %>
</h3>
<%= render partial: "select_team", locals: { project: project } %>
<%= link_to "Add ToDo Item", new_project_item_path(project.id) %>
<%= link_to "Edit Details", edit_project_path(project.id) %>
<%= button_to "Remove Project", project_path(project.id),
								method: :delete, confirm: "Are you sure?" %>
<h3>Description</h3>
<p><%= project.description %><p>
<h4><em>To Do</em></h4>
<%= render partial: "items/items", object: project.items %>

app/views/projects/_select_team.html.erb
<%= form_for(project) do |f| %>
	<label>
		Assigned Team
		<%= f.collection_select :team_id, Team.all, :id, :name %>
	</label>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit This Project</h1>
<%= render partial: "form" %>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<%= link_to "New Project", new_project_path %>
<% @projects.each do |project| %>
 <h3>--------------------------------------------------</h3>
 <%= render partial: "project", object: project%>
<% end %>

app/views/projects/new.html.erb
<h1>Create a New Project</h1>
<%= render partial: "form" %>

app/views/projects/show.html.erb
<h1>Project Details</h1>
<%= render partial: "project", object: @project %>